services:
  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
    ports:
      - '4090:4080'
    volumes:
      - ./zinc:/var/lib/zinc
  api:
    build: ./api
    ports:
      - 3334:3000
    depends_on:
      - zinc
    #restart: on-failure
