services:
  zinc:
    image: public.ecr.aws/zinclabs/zinc:latest
    environment:
      - ZINC_FIRST_ADMIN_USER=admin
      - ZINC_FIRST_ADMIN_PASSWORD=Complexpass#123
    ports:
      - '4090:4080'
    volumes:
      - ./zinc:/var/lib/zinc
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    environment:
      - API_PORT= 3000
      - ZS_USER= admin
      - ZS_PASSWORD= Complexpass#123
      - ZS_BASE_URL= http://localhost:4090
      - ZS_INDEX_NAME= mail
    ports:
      - 3000:3000
    depends_on:
      - zinc
    restart: on-failure
    volumes:
      - ./server:/usr/src/app
  